<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title' => ['en' => 'The Prophet', 'ar' => 'النبي'],
                'description' => ['en' => 'A philosophical book by Kahlil Gibran.', 'ar' => 'كتاب فلسفي لجبران خليل جبران.'],
                'publish_date' => '1923-09-01',
                'book_pdf' => 'the_prophet.pdf',
                'cover_image' => 'the_prophet_cover.webp',
                'number_of_pages' => 122,
                'summary' => ['en' => 'https://youtu.be/n5g8Q_90r9E?si=AC7UOYdxjS7YcFRQ', 'ar' => 'https://youtu.be/i_tFeYr6kXY?si=63poXBaCPCjAv6aD'],
                'author_id' => 2,
                'category_id' => 7,
                'size_category_id' => 1,
                'points' =>60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => ['en' => 'Season of Migration to the North', 'ar' => 'موسم الهجرة إلى الشمال'],
                'description' => ['en' => 'A postcolonial novel by Tayeb Salih.', 'ar' => 'رواية من الأدب السوداني للطيب صالح.'],
                'publish_date' => '1966-01-01',
                'book_pdf' => 'Season-of-Migration-to-the-North-Tayeb-Salih-novel.pdf',
                'cover_image' => 'migration_cover.webp',
                'number_of_pages' => 118,
                'summary' => ['en' => 'https://youtu.be/QB52ltMl3H8?si=PxCKaBJGW-jBdd5z', 'ar' => 'https://youtu.be/mPK5emajngc?si=ZBl0Y8X_isw05uRl'],
                'author_id' => 2,
                'category_id' => 5,
                'size_category_id' => 1,
                'points' =>50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => ['en' => 'Men in the Sun', 'ar' => 'رجال في الشمس'],
                'description' => ['en' => 'A novel by Ghassan Kanafani.', 'ar' => 'رواية للكاتب الفلسطيني غسان كنفاني.'],
                'publish_date' => '1963-01-01',
                'book_pdf' => 'men_in_the_sun.pdf',
                'cover_image' => 'men_in_the_sun_cover.webp',
                'number_of_pages' => 46,
                'summary' => ['en' => 'https://youtu.be/McQP7VFmY0w?si=4LOc9mxmHLgTPYYN', 'ar' => 'https://youtu.be/jDgtYzgv-mA?si=lHEUtbDGvzIxpFya'],
                'author_id' => 3,
                'category_id' => 5,
                'size_category_id' => 1,
                'points' =>25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
            'title' => ['en' => 'The Magic Shop', 'ar' => 'دكان السحر'],
            'description' => ['en' => 'A mysterious shop with terrifying secrets.', 'ar' => 'دكان غامض يبيع أدوات سحرية تسبب كوارث.'],
            'publish_date' => '1927-04-01',
             'book_pdf' => 'the_magic_shop.pdf',
             'cover_image' => 'magic_shop_cover.webp',
             'number_of_pages' => 11,
             'summary' => ['en' => 'https://youtu.be/js-Ne9Wd4ms?si=QjCZ2FF9J2CxB25F', 'ar' => 'https://youtu.be/PUnD6SN8ciA?si=vQmGhOdUQrBiIfNx'],
             'author_id' => 8,
            'category_id' => 2,
            'size_category_id' => 1,
            'points' =>10,
             'created_at' => now(),
            'updated_at' => now(),
            ],
            [
                'title' => ['en' => 'Memory in the Flesh', 'ar' => 'ذاكرة الجسد'],
                'description' => ['en' => 'A romantic and political novel by Ahlam Mosteghanemi.', 'ar' => 'رواية رومانسية سياسية لأحلام مستغانمي.'],
                'publish_date' => '1993-01-01',
                'book_pdf' => 'memory_in_the_flesh.pdf',
                'cover_image' => 'memory_in_the_flesh_cover.jpeg',
                'number_of_pages' => 406,
                 'summary' => ['en' => 'https://youtu.be/QJCLI_SYxRY?si=F6NmtwohnQqqa_gR', 'ar' => 'https://youtu.be/sMThU0RfoR8?si=rEKUM-nCY05xyf36'],
                'author_id' => 8,
                'category_id' => 3,
                'size_category_id' => 3,
                'points' =>190,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => ['en' => 'The Open Door', 'ar' => 'الباب المفتوح'],
                'description' => ['en' => 'A feminist novel by Latifa al-Zayyat.', 'ar' => 'رواية نسوية للكاتبة لطيفة الزيات.'],
                'publish_date' => '1960-01-01',
                'book_pdf' => 'the_open_door.pdf',
                'cover_image' => 'the_open_door_cover.jpeg',
                'number_of_pages' => 360,
                 'summary' => ['en' => 'https://youtu.be/neJep2Bdv0k?si=VKj_AHGRhNGSQI_1', 'ar' => 'https://youtu.be/eVkgPFFmWCM?si=AIBU7WwX-_y8Z3Fk'],
                'author_id' => 2,
                'category_id' => 3,
                'size_category_id' => 2,
                'points' =>170,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => ['en' => 'Cities of Salt', 'ar' => 'مدن الملح'],
                'description' => ['en' => 'A critical novel by Abdelrahman Munif.', 'ar' => 'رواية نقدية لعبد الرحمن منيف.'],
                'publish_date' => '1984-01-01',
                'book_pdf' => 'cities_of_salt.pdf',
                'cover_image' => 'cities_cover.jpeg',
                'number_of_pages' => 611,
                 'summary' => ['en' => 'https://youtu.be/qzxZzUXlnsQ?si=vGjrPA-BTOq6axl0', 'ar' => null],
                'author_id' => 2,
                'category_id' => 5,
                'size_category_id' => 3,
                'points' =>210,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => ['en' => 'Yacoubian Building', 'ar' => 'عمارة يعقوبيان'],
                'description' => ['en' => 'A novel that depicts modern Cairo by Alaa Al Aswany.', 'ar' => 'رواية تجسد القاهرة الحديثة للكاتب علاء الأسواني.'],
                'publish_date' => '2002-01-01',
                'book_pdf' => 'Yacoubian_Building.pdf',
                'cover_image' => 'Yacoubian_Building_cover.jpeg',
                'number_of_pages' => 341,
                'summary' => ['en' => 'https://youtu.be/y9qvIfpkhn8?si=qvgEQa9-LMStxRne', 'ar' => 'https://youtu.be/VGbubth8Zao?si=9PS0ei_aBKAClqdo'],
                'author_id' => 8,
                'category_id' => 2,
                'size_category_id' => 2,
                'points' =>160,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => ['en' => 'The Bamboo Stalk', 'ar' => 'ساق البامبو'],
                'description' => ['en' => 'A novel by Saud Alsanousi about identity.', 'ar' => 'رواية عن الهوية للكاتب سعود السنعوسي.'],
                'publish_date' => '2012-01-01',
                'book_pdf' => 'bamboo_stalk.pdf',
                'cover_image' => 'bamboo_cover.jpeg',
                'number_of_pages' => 25,
                'summary' => ['en' => 'https://youtu.be/ImpE8qQiaro?si=VTQeCdxibNr7Jl1a', 'ar' => 'https://youtu.be/tHoUxqqcpp8?si=oTlpVKq3yWBpBPm6'],
                'author_id' => 2,
                'category_id' => 3,
                'size_category_id' => 1,
                'points' =>15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => ['en' => 'Frankenstein in Baghdad', 'ar' => 'فرانكنشتاين في بغداد'],
                'description' => ['en' => 'A novel by Ahmed Saadawi blending horror and war.', 'ar' => 'رواية تجمع بين الرعب والحرب للكاتب أحمد سعداوي.'],
                'publish_date' => '2013-01-01',
                'book_pdf' => 'frankenstein_baghdad.pdf',
                'cover_image' => 'frankenstein_cover.webp',
                'number_of_pages' => 203,
                'summary' => ['en' => 'https://youtu.be/26cigmNyn5Q?si=vW4T1pZb9iGagOCP', 'ar' => 'https://youtu.be/jn9r-lew_OI?si=V_Y2kI-kxe_z6o8m'],
                'author_id' => 2,
                'category_id' => 4,
                'size_category_id' => 2,
                'points' =>190,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($books as $book) {
            DB::table('books')->insert([
                'title' => json_encode($book['title'], JSON_UNESCAPED_UNICODE),
                'description' => json_encode($book['description'], JSON_UNESCAPED_UNICODE),
                'publish_date' => $book['publish_date'],
                'book_pdf' => $book['book_pdf'],
                'cover_image' => $book['cover_image'],
                'number_of_pages' => $book['number_of_pages'],
                'summary' => json_encode($book['summary'], JSON_UNESCAPED_UNICODE),
                'author_id' => $book['author_id'],
                'category_id' => $book['category_id'],
                'size_category_id' => $book['size_category_id'],
                'created_at' => $book['created_at'],
                'updated_at' => $book['updated_at'],
            ]);
        }
    }
}
