<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       $books=
    [[
        'title' => ['en' => 'The Prophet', 'ar' => 'النبي'],
        'description' => ['en' => 'A philosophical book by Kahlil Gibran.', 'ar' => 'كتاب فلسفي لجبران خليل جبران.'],
        'publish_date' => '1923-09-01',
        'book_pdf' => 'the_prophet.pdf',
        'image_cover' => 'the_prophet_cover.jpg',
        'star_rate' => 5,
        'number_of_pages' => 150,
        'is_challenged' => false,
        'author_id' => 2,
        'category_id' => 1,
        'size_category_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
      ],
    [
        'title' => ['en' => 'Season of Migration to the North', 'ar' => 'موسم الهجرة إلى الشمال'],
        'description' => ['en' => 'A postcolonial novel by Tayeb Salih.', 'ar' => 'رواية من الأدب السوداني للطيب صالح.'],
        'publish_date' => '1966-01-01',
        'book_pdf' => 'migration_north.pdf',
        'image_cover' => 'migration_cover.jpg',
        'star_rate' => 4,
        'number_of_pages' => 200,
        'is_challenged' => true,
        'author_id' => 2,
        'category_id' => 2,
        'size_category_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => ['en' => 'Men in the Sun', 'ar' => 'رجال في الشمس'],
        'description' => ['en' => 'A novel by Ghassan Kanafani.', 'ar' => 'رواية للكاتب الفلسطيني غسان كنفاني.'],
        'publish_date' => '1963-01-01',
        'book_pdf' => 'men_in_the_sun.pdf',
        'image_cover' => 'men_in_the_sun_cover.jpg',
        'star_rate' => 4,
        'number_of_pages' => 120,
        'is_challenged' => true,
        'author_id' => 3,
        'category_id' => 1,
        'size_category_id' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => ['en' => 'Palace Walk', 'ar' => 'بين القصرين'],
        'description' => ['en' => 'The first part of Naguib Mahfouz\'s Cairo Trilogy.', 'ar' => 'الجزء الأول من ثلاثية القاهرة لنجيب محفوظ.'],
        'publish_date' => '1956-01-01',
        'book_pdf' => 'palace_walk.pdf',
        'image_cover' => 'palace_walk_cover.jpg',
        'star_rate' => 5,
        'number_of_pages' => 350,
        'is_challenged' => false,
        'author_id' => 4,
        'category_id' => 1,
        'size_category_id' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => ['en' => 'Memory in the Flesh', 'ar' => 'ذاكرة الجسد'],
        'description' => ['en' => 'A romantic and political novel by Ahlam Mosteghanemi.', 'ar' => 'رواية رومانسية سياسية لأحلام مستغانمي.'],
        'publish_date' => '1993-01-01',
        'book_pdf' => 'memory_in_the_flesh.pdf',
        'image_cover' => 'memory_cover.jpg',
        'star_rate' => 5,
        'number_of_pages' => 320,
        'is_challenged' => false,
        'author_id' => 5,
        'category_id' => 2,
        'size_category_id' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => ['en' => 'The Open Door', 'ar' => 'الباب المفتوح'],
        'description' => ['en' => 'A feminist novel by Latifa al-Zayyat.', 'ar' => 'رواية نسوية للكاتبة لطيفة الزيات.'],
        'publish_date' => '1960-01-01',
        'book_pdf' => 'the_open_door.pdf',
        'image_cover' => 'the_open_door_cover.jpg',
        'star_rate' => 4,
        'number_of_pages' => 280,
        'is_challenged' => true,
        'author_id' => 2,
        'category_id' => 3,
        'size_category_id' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => ['en' => 'Cities of Salt', 'ar' => 'مدن الملح'],
        'description' => ['en' => 'A critical novel by Abdelrahman Munif.', 'ar' => 'رواية نقدية لعبد الرحمن منيف.'],
        'publish_date' => '1984-01-01',
        'book_pdf' => 'cities_of_salt.pdf',
        'image_cover' => 'cities_cover.jpg',
        'star_rate' => 5,
        'number_of_pages' => 450,
        'is_challenged' => false,
        'author_id' => 2,
        'category_id' => 4,
        'size_category_id' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => ['en' => 'Yacoubian Building', 'ar' => 'عمارة يعقوبيان'],
        'description' => ['en' => 'A novel that depicts modern Cairo by Alaa Al Aswany.', 'ar' => 'رواية تجسد القاهرة الحديثة للكاتب علاء الأسواني.'],
        'publish_date' => '2002-01-01',
        'book_pdf' => 'yacoubian.pdf',
        'image_cover' => 'yacoubian_cover.jpg',
        'star_rate' => 4,
        'number_of_pages' => 330,
        'is_challenged' => true,
        'author_id' => 8,
        'category_id' => 2,
        'size_category_id' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => ['en' => 'The Bamboo Stalk', 'ar' => 'ساق البامبو'],
        'description' => ['en' => 'A novel by Saud Alsanousi about identity.', 'ar' => 'رواية عن الهوية للكاتب سعود السنعوسي.'],
        'publish_date' => '2012-01-01',
        'book_pdf' => 'bamboo_stalk.pdf',
        'image_cover' => 'bamboo_cover.jpg',
        'star_rate' => 5,
        'number_of_pages' => 400,
        'is_challenged' => false,
        'author_id' => 2,
        'category_id' => 4,
        'size_category_id' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => ['en' => 'Frankenstein in Baghdad', 'ar' => 'فرانكنشتاين في بغداد'],
        'description' => ['en' => 'A novel by Ahmed Saadawi blending horror and war.', 'ar' => 'رواية تجمع بين الرعب والحرب للكاتب أحمد سعداوي.'],
        'publish_date' => '2013-01-01',
        'book_pdf' => 'frankenstein_baghdad.pdf',
        'image_cover' => 'frankenstein_cover.jpg',
        'star_rate' => 4,
        'number_of_pages' => 280,
        'is_challenged' => false,
        'author_id' => 2,
        'category_id' => 5,
        'size_category_id' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
        ];
 foreach ($books as $book) {
    DB::table('books')->insert([
        'title' => json_encode($book['title'], JSON_UNESCAPED_UNICODE),
        'description' => json_encode($book['description'], JSON_UNESCAPED_UNICODE),
        'publish_date' => $book['publish_date'],
        'book_pdf' => $book['book_pdf'],
        'image_cover' => $book['image_cover'],
        'star_rate' => $book['star_rate'],
        'number_of_pages' => $book['number_of_pages'],
        'is_challenged' => $book['is_challenged'],
        'author_id' => $book['author_id'],
        'category_id' => $book['category_id'],
        'size_category_id' => $book['size_category_id'],
        'created_at' => $book['created_at'],
        'updated_at' => $book['updated_at'],
    ]);
}
    }
}
